import { Restaurant, Product, Language } from './types';

const sakhinkleProductsRaw: Omit<Product, 'id' | 'restaurants'>[] = [
    { name_ka: '12 მარცვალი', name_en: '12 Grains', name_ru: '12 Зерен', category_ka: 'ლუდი', category_en: 'Beer', category_ru: 'Пиво', defaultUnit: 'ცალი' },
    { name_ka: 'აჯინო', name_en: 'Ajino', name_ru: 'Аджино', category_ka: 'სუნელები', category_en: 'Spices', category_ru: 'Специи', defaultUnit: 'კგ' },
    { name_ka: 'ბორჯომი', name_en: 'Borjomi', name_ru: 'Боржоми', category_ka: 'სასმელები', category_en: 'Drinks', category_ru: 'Напитки', defaultUnit: 'ცალი' },
    { name_ka: 'ზეთი', name_en: 'Oil', name_ru: 'Масло', category_ka: 'ზეთები', category_en: 'Oils', category_ru: 'Масла', defaultUnit: 'ლიტრი' },
    { name_ka: 'ზეთი ზეითუნის', name_en: 'Olive Oil', name_ru: 'Оливковое масло', category_ka: 'ზეთები', category_en: 'Oils', category_ru: 'Масла', defaultUnit: 'ლიტრი' },
    { name_ka: 'კარაქი', name_en: 'Butter', name_ru: 'Сливочное масло', category_ka: 'რძის პროდუქტები', category_en: 'Dairy', category_ru: 'Молочные продукты', defaultUnit: 'კგ' },
    { name_ka: 'კიტრი', name_en: 'Cucumber', name_ru: 'Огурец', category_ka: 'ბოსტნეული', category_en: 'Vegetables', category_ru: 'Овощи', defaultUnit: 'კგ' },
    { name_ka: 'კოლა', name_en: 'Cola', name_ru: 'Кола', category_ka: 'სასმელები', category_en: 'Drinks', category_ru: 'Напитки', defaultUnit: 'ცალი' },
    { name_ka: 'კოწახური', name_en: 'Barberry', name_ru: 'Барбарис', category_ka: 'სუნელები', category_en: 'Spices', category_ru: 'Специи', defaultUnit: 'კგ' },
    { name_ka: 'ლაგერი', name_en: 'Lager', name_ru: 'Лагер', category_ka: 'ლუდი', category_en: 'Beer', category_ru: 'Пиво', defaultUnit: 'ცალი' },
    { name_ka: 'ლიმონათი', name_en: 'Lemonade', name_ru: 'Лимонад', category_ka: 'სასმელები', category_en: 'Drinks', category_ru: 'Напитки', defaultUnit: 'ცალი' },
    { name_ka: 'მარილი', name_en: 'Salt', name_ru: 'Соль', category_ka: 'სუნელები', category_en: 'Spices', category_ru: 'Специи', defaultUnit: 'კგ' },
    { name_ka: 'მჟავე', name_en: 'Pickles', name_ru: 'Соленья', category_ka: 'ბოსტნეული', category_en: 'Vegetables', category_ru: 'Овощи', defaultUnit: 'კგ' },
    { name_ka: 'ნიგოზი', name_en: 'Walnut', name_ru: 'Грецкий орех', category_ka: 'თხილეული', category_en: 'Nuts', category_ru: 'Орехи', defaultUnit: 'კგ' },
    { name_ka: 'ნიორი', name_en: 'Garlic', name_ru: 'Чеснок', category_ka: 'ბოსტნეული', category_en: 'Vegetables', category_ru: 'Овощи', defaultUnit: 'კგ' },
    { name_ka: 'ოხრახუში', name_en: 'Parsley', name_ru: 'Петрушка', category_ka: 'მწვანილი', category_en: 'Herbs', category_ru: 'Зелень', defaultUnit: 'შეკვრა' },
    { name_ka: 'პომიდორი', name_en: 'Tomato', name_ru: 'Помидор', category_ka: 'ბოსტნეული', category_en: 'Vegetables', category_ru: 'Овощи', defaultUnit: 'კგ' },
    { name_ka: 'პური ნაყიდი', name_en: 'Purchased Bread', name_ru: 'Покупной хлеб', category_ka: 'პურ-ფუნთუშეული', category_en: 'Bakery', category_ru: 'Выпечка', defaultUnit: 'ცალი' },
    { name_ka: 'რეჰანი', name_en: 'Basil', name_ru: 'Базилик', category_ka: 'მწვანილი', category_en: 'Herbs', category_ru: 'Зелень', defaultUnit: 'შეკვრა' },
    { name_ka: 'რქაწითელი', name_en: 'Rkatsiteli', name_ru: 'Ркацители', category_ka: 'ღვინო', category_en: 'Wine', category_ru: 'Вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'საფერავი', name_en: 'Saperavi', name_ru: 'Саперави', category_ka: 'ღვინო', category_en: 'Wine', category_ru: 'Вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'საფუარი', name_en: 'Yeast', name_ru: 'Дрожжи', category_ka: 'სხვა', category_en: 'Other', category_ru: 'Прочее', defaultUnit: 'კგ' },
    { name_ka: 'ხინკლის ხორცი', name_en: 'Khinkali Meat', name_ru: 'Мясо для хинкали', category_ka: 'ხორცი', category_en: 'Meat', category_ru: 'Мясо', defaultUnit: 'კგ' },
    { name_ka: 'სახაშლამე ხორცი', name_en: 'Khashlama Meat', name_ru: 'Мясо для хашламы', category_ka: 'ხორცი', category_en: 'Meat', category_ru: 'Мясо', defaultUnit: 'კგ' },
    { name_ka: 'სოიო მიქსი', name_en: 'Soy Mix', name_ru: 'Соевый микс', category_ka: 'სოუსები', category_en: 'Sauces', category_ru: 'Соусы', defaultUnit: 'ლიტრი' },
    { name_ka: 'სულგუნი', name_en: 'Sulguni', name_ru: 'Сулгуни', category_ka: 'რძის პროდუქტები', category_en: 'Dairy', category_ru: 'Молочные продукты', defaultUnit: 'კგ' },
    { name_ka: 'ფქვილი', name_en: 'Flour', name_ru: 'Мука', category_ka: 'ბურღულეული', category_en: 'Grains', category_ru: 'Крупы', defaultUnit: 'კგ' },
    { name_ka: 'ქინძი', name_en: 'Coriander', name_ru: 'Кинза', category_ka: 'მწვანილი', category_en: 'Herbs', category_ru: 'Зелень', defaultUnit: 'შეკვრა' },
    { name_ka: 'ქინძმარაული', name_en: 'Kindzmarauli', name_ru: 'Киндзмараули', category_ka: 'ღვინო', category_en: 'Wine', category_ru: 'Вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'ქისი', name_en: 'Kisi', name_ru: 'Киси', category_ka: 'ღვინო', category_en: 'Wine', category_ru: 'Вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'ღორის სალა', name_en: 'Pork Fat (Salo)', name_ru: 'Свиное сало', category_ka: 'ხორცი', category_en: 'Meat', category_ru: 'Мясо', defaultUnit: 'კგ' },
    { name_ka: 'ღორის ხორცი (სამწვადე)', name_en: 'Pork (for Mtsvadi)', name_ru: 'Свинина (для шашлыка)', category_ka: 'ხორცი', category_en: 'Meat', category_ru: 'Мясо', defaultUnit: 'კგ' },
    { name_ka: 'ყველი იმერული', name_en: 'Imeretian Cheese', name_ru: 'Имеретинский сыр', category_ka: 'რძის პროდუქტები', category_en: 'Dairy', category_ru: 'Молочные продукты', defaultUnit: 'კგ' },
    { name_ka: 'შაქარი', name_en: 'Sugar', name_ru: 'Сахар', category_ka: 'სხვა', category_en: 'Other', category_ru: 'Прочее', defaultUnit: 'კგ' },
    { name_ka: 'ცომი', name_en: 'Dough', name_ru: 'Тесто', category_ka: 'პურ-ფუნთუშეული', category_en: 'Bakery', category_ru: 'Выпечка', defaultUnit: 'კგ' },
    { name_ka: 'ძირა', name_en: 'Cumin', name_ru: 'Тмин', category_ka: 'სუნელები', category_en: 'Spices', category_ru: 'Специи', defaultUnit: 'კგ' },
    { name_ka: 'ძმარი', name_en: 'Vinegar', name_ru: 'Уксус', category_ka: 'სხვა', category_en: 'Other', category_ru: 'Прочее', defaultUnit: 'ლიტრი' },
    { name_ka: 'წყალი', name_en: 'Water', name_ru: 'Вода', category_ka: 'სასმელები', category_en: 'Drinks', category_ru: 'Напитки', defaultUnit: 'ლიტრი' },
    { name_ka: 'წყალი ბოთლის', name_en: 'Bottled Water', name_ru: 'Вода в бутылках', category_ka: 'სასმელები', category_en: 'Drinks', category_ru: 'Напитки', defaultUnit: 'ცალი' },
    { name_ka: 'ხახვი', name_en: 'Onion', name_ru: 'Лук', category_ka: 'ბოსტნეული', category_en: 'Vegetables', category_ru: 'Овощи', defaultUnit: 'კგ' },
];

const midiebiProductsRaw: Omit<Product, 'id' | 'restaurants'>[] = [
    { name_ka: 'Ambrosiac/ თავკვერი 2022', name_en: 'Ambrosiac/ Tavkveri 2022', name_ru: 'Амброзиак/ Тавквери 2022', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Ancho Reyes Original Chilly', name_en: 'Ancho Reyes Original Chilly', name_ru: 'Анчо Рейес Оригинал Чили', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Anthos Rkatsiteli 2018 ROSHA', name_en: 'Anthos Rkatsiteli 2018 ROSHA', name_ru: 'Антос Ркацители 2018 РОША', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Anthos Rkatsiteli 2019 ROSHA', name_en: 'Anthos Rkatsiteli 2019 ROSHA', name_ru: 'Антос Ркацители 2019 РОША', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ArtSpritze Aperativo', name_en: 'ArtSpritze Aperativo', name_ru: 'АртСпритце Аперативо', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Brandy Askaneli', name_en: 'Brandy Askaneli', name_ru: 'Бренди Асканели', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Captain Morgan Black', name_en: 'Captain Morgan Black', name_ru: 'Капитан Морган Блэк', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Chacha Askaneli', name_en: 'Chacha Askaneli', name_ru: 'Чача Асканели', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Chelti Khikhvi EU', name_en: 'Chelti Khikhvi EU', name_ru: 'Челти Хихви ЕС', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'chinuri ჩინური', name_en: 'Chinuri', name_ru: 'Чинури', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Danzka 40%', name_en: 'Danzka 40%', name_ru: 'Данска 40%', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'DANZKA 50%', name_en: 'DANZKA 50%', name_ru: 'ДАНСКА 50%', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'EL Calipote Dark Rum', name_en: 'EL Calipote Dark Rum', name_ru: 'Эль Калипоте Темный Ром', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Gravitas Kisi-Khikhvi 2020 ROSHA', name_en: 'Gravitas Kisi-Khikhvi 2020 ROSHA', name_ru: 'Гравитас Киси-Хихви 2020 РОША', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Inedit Beer', name_en: 'Inedit Beer', name_ru: 'Пиво Инедит', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'INOLA/წქაწითელი ქისი როშა 2022', name_en: 'INOLA/Rkatsiteli Kisi Rosha 2022', name_ru: 'ИНОЛА/Ркацители Киси Роша 2022', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Jim Beam Burbon', name_en: 'Jim Beam Bourbon', name_ru: 'Джим Бим Бурбон', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Khikhvi IBERO', name_en: 'Khikhvi IBERO', name_ru: 'Хихви ИБЕРО', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Kilbeggan Irish whisky', name_en: 'Kilbeggan Irish whisky', name_ru: 'Килбегган Ирландский виски', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'KINDZMARAULI HOMEMADE', name_en: 'KINDZMARAULI HOMEMADE', name_ru: 'КИНДЗМАРАУЛИ ДОМАШНЕЕ', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'Kirke Vodka', name_en: 'Kirke Vodka', name_ru: 'Водка Кирке', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Kisi IBERO', name_en: 'Kisi IBERO', name_ru: 'Киси ИБЕРО', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Marakuia Fontana', name_en: 'Maracuya Fontana', name_ru: 'Маракуйя Фонтана', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Martini Bianco', name_en: 'Martini Bianco', name_ru: 'Мартини Бьянко', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Martini Rosso', name_en: 'Martini Rosso', name_ru: 'Мартини Россо', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Monin Curacao Triple Sec', name_en: 'Monin Curacao Triple Sec', name_ru: 'Монин Кюрасао Трипл Сек', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Moonwalker Gin', name_en: 'Moonwalker Gin', name_ru: 'Джин Мунволкер', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Moonwalker whisky', name_en: 'Moonwalker whisky', name_ru: 'Виски Мунволкер', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Mtsvane / Wine Well', name_en: 'Mtsvane / Wine Well', name_ru: 'Мцване / Вайн Велл', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Mtsvane IBERO', name_en: 'Mtsvane IBERO', name_ru: 'Мцване ИБЕРО', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'mtsvane მწვანე', name_en: 'Mtsvane', name_ru: 'Мцване', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Napareuli Saperavi ROSHA', name_en: 'Napareuli Saperavi ROSHA', name_ru: 'Напареули Саперави РОША', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Prosecco Tosti', name_en: 'Prosecco Tosti', name_ru: 'Просекко Тости', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Rkatsiteli IBERO', name_en: 'Rkatsiteli IBERO', name_ru: 'Ркацители ИБЕРО', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Saperavi / Wine Well / BIO', name_en: 'Saperavi / Wine Well / BIO', name_ru: 'Саперави / Вайн Велл / БИО', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Saperavi IBERO', name_en: 'Saperavi IBERO', name_ru: 'Саперави ИБЕРО', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Sparkling Wine', name_en: 'Sparkling Wine', name_ru: 'Игристое вино', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Timothee Rkatsiteli-Mwvane 2020 ROSHA', name_en: 'Timothee Rkatsiteli-Mwvane 2020 ROSHA', name_ru: 'Тимоте Ркацители-Мцване 2020 РОША', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Tonic Moonwalker', name_en: 'Tonic Moonwalker', name_ru: 'Тоник Мунволкер', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Udabno/თავკვერი-საფერავი როშა, 2022', name_en: 'Udabno/Tavkveri-Saperavi Rosha, 2022', name_ru: 'Удабно/Тавквери-Саперави Роша, 2022', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Vermilion/საფერავი,2018', name_en: 'Vermilion/Saperavi, 2018', name_ru: 'Вермилион/Саперави, 2018', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'Vodka', name_en: 'Vodka', name_ru: 'Водка', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'Whisky', name_en: 'Whisky', name_ru: 'Виски', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'Wine Well / Rkatsiteli Amber BIO', name_en: 'Wine Well / Rkatsiteli Amber BIO', name_ru: 'Вайн Велл / Ркацители Амбер БИО', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'აპა', name_en: 'APA', name_ru: 'АПА', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'აპეროლი', name_en: 'Aperol', name_ru: 'Апероль', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ასკანელო ვს', name_en: 'Askanelo VS', name_ru: 'Асканело ВС', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ბრენდი', name_en: 'Brandy', name_ru: 'Бренди', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'გორული მწვანე პეტნატი', name_en: 'Goruli Mtsvane Petnat', name_ru: 'Горули Мцване Петнат', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'გორული ჩინური მწვანე ქვევრი', name_en: 'Goruli Chinuri Mtsvane Qvevri', name_ru: 'Горули Чинури Мцване Квеври', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'გრენადინი', name_en: 'Grenadine', name_ru: 'Гренадин', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'თეთრი რომი', name_en: 'White Rum', name_ru: 'Белый ром', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'თეთრი ჩელთი მუხაში', name_en: 'White Chelti in Oak', name_ru: 'Белый Челти в дубе', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'თიფსი ბეიბი ჩელთი', name_en: 'Tipsy Baby Chelti', name_ru: 'Типси Бейби Челти', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'იპა', name_en: 'IPA', name_ru: 'ИПА', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'კამპარი', name_en: 'Campari', name_ru: 'Кампари', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'კურვუაზიე კონიაკი', name_en: 'Courvoisier Cognac', name_ru: 'Коньяк Курвуазье', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'მანავის მწვანე სახლური', name_en: 'Manavis Mtsvane Homemade', name_ru: 'Манавис Мцване Домашнее', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'მუხაში დაძველებული თეთრი', name_en: 'Oak Aged White', name_ru: 'Белое, выдержанное в дубе', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'რქაწითელი ევროპული', name_en: 'European Rkatsiteli', name_ru: 'Ркацители Европейское', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'რქაწითელი სახლური ევროპული', name_en: 'Homemade European Rkatsiteli', name_ru: 'Домашнее Европейское Ркацители', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'სამზარეულოს ღვინო', name_en: 'Cooking Wine', name_ru: 'Кулинарное вино', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'საფერავი', name_en: 'Saperavi', name_ru: 'Саперави', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'საფერავი კლასიკური ჩელთი', name_en: 'Saperavi Classic Chelti', name_ru: 'Саперави Классик Челти', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'საფერავი სახლური', name_en: 'Homemade Saperavi', name_ru: 'Домашнее Саперави', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'შუშხუნა ღვინო', name_en: 'Sparkling Wine', name_ru: 'Игристое вино', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ჩინური-გორული მწვანე სოლომონე ბოთლი', name_en: 'Chinuri-Goruli Mtsvane Solomone Bottle', name_ru: 'Чинури-Горули Мцване Соломоне Бутылка', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ჩიჩე 3 ყურძენი ბოთლი', name_en: 'Chiche 3 Grapes Bottle', name_ru: 'Чиче 3 Винограда Бутылка', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ციცქა კრახუნა', name_en: 'Tsitska-Krakhuna', name_ru: 'Цицка-Крахуна', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ციცქა კრახუნა ჩელთი', name_en: 'Tsitska-Krakhuna Chelti', name_ru: 'Цицка-Крахуна Челти', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ცოლიკაური პეტნატი', name_en: 'Tsolikouri Petnat', name_ru: 'Цоликоури Петнат', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ძელშავი პეტნატი', name_en: 'Dzelshavi Petnat', name_ru: 'Дзелшави Петнат', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'წინანდალი', name_en: 'Tsinandali', name_ru: 'Цинандали', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'წინანდალი სახლური ევროპული', name_en: 'Homemade European Tsinandali', name_ru: 'Домашнее Европейское Цинандали', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ლიტრი' },
    { name_ka: 'წინანდალი ჩელთი', name_en: 'Tsinandali Chelti', name_ru: 'Цинандали Челти', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ხიხვი', name_en: 'Khikhvi', name_ru: 'Хихви', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ხიხვი პირველი', name_en: 'Khikhvi First', name_ru: 'Хихви Первый', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ჯინი "Jako"', name_en: 'Gin "Jako"', name_ru: 'Джин "Jako"', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ჯინჯერ ლუდი', name_en: 'Ginger Beer', name_ru: 'Имбирное пиво', category_ka: 'ალკოჰოლური სასმელები და ღვინო', category_en: 'Alcoholic beverages and wine', category_ru: 'Алкогольные напитки и вино', defaultUnit: 'ცალი' },
    { name_ka: 'ბეკონი', name_en: 'Bacon', name_ru: 'Бекон', category_ka: 'ხორცი და ხორცპროდუქტები', category_en: 'Meat and meat products', category_ru: 'Мясо и мясные продукты', defaultUnit: 'კგ' },
    { name_ka: 'თიბოუნ სტეიკი', name_en: 'T-bone steak', name_ru: 'Т-боун стейк', category_ka: 'ხორცი და ხორცპროდუქტები', category_en: 'Meat and meat products', category_ru: 'Мясо и мясные продукты', defaultUnit: 'კგ' },
    { name_ka: 'ლორი', name_en: 'Ham', name_ru: 'Ветчина', category_ka: 'ხორცი და ხორცპროდუქტები', category_en: 'Meat and meat products', category_ru: 'Мясо и мясные продукты', defaultUnit: 'კგ' },
    { name_ka: 'რიბაი სტეიკი', name_en: 'Ribeye steak', name_ru: 'Стейк рибай', category_ka: 'ხორცი და ხორცპროდუქტები', category_en: 'Meat and meat products', category_ru: 'Мясо и мясные продукты', defaultUnit: 'კგ' },
    { name_ka: 'სოსისი ივერია', name_en: 'Sausage Iveria', name_ru: 'Сосиски Иверия', category_ka: 'ხორცი და ხორცპროდუქტები', category_en: 'Meat and meat products', category_ru: 'Мясо и мясные продукты', defaultUnit: 'კგ' },
    { name_ka: 'ღორის კისერი', name_en: 'Pork neck', name_ru: 'Свиная шея', category_ka: 'ხორცი და ხორცპროდუქტები', category_en: 'Meat and meat products', category_ru: 'Мясо и мясные продукты', defaultUnit: 'კგ' },
    { name_ka: 'ღორის ნეკნები', name_en: 'Pork ribs', name_ru: 'Свиные ребрышки', category_ka: 'ხორცი და ხორცპროდუქტები', category_en: 'Meat and meat products', category_ru: 'Мясо и мясные продукты', defaultUnit: 'კგ' },
    { name_ka: 'ქათმის ფილე', name_en: 'Chicken fillet', name_ru: 'Куриное филе', category_ka: 'ხორცი და ხორცპროდუქტები', category_en: 'Meat and meat products', category_ru: 'Мясо и мясные продукты', defaultUnit: 'კგ' },
    { name_ka: 'ქათმის ღვიძლი', name_en: 'Chicken liver', name_ru: 'Куриная печень', category_ka: 'ხორცი და ხორცპროდუქტები', category_en: 'Meat and meat products', category_ru: 'Мясо и мясные продукты', defaultUnit: 'კგ' },
    { name_ka: 'ანჩოუსი', name_en: 'Anchovy', name_ru: 'Анчоусы', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'ბარაბულკა', name_en: 'Red mullet', name_ru: 'Барабулька', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'დიდი მიდიები', name_en: 'Big mussels', name_ru: 'Большие мидии', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'დიდი რვაფეხა', name_en: 'Big octopus', name_ru: 'Большой осьминог', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'დორადო', name_en: 'Dorado', name_ru: 'Дорадо', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'კალმარი', name_en: 'Squid', name_ru: 'Кальмар', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'კალმახი', name_en: 'Trout', name_ru: 'Форель', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'კრევეტები', name_en: 'Shrimp', name_ru: 'Креветки', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'ლობსტერი', name_en: 'Lobster', name_ru: 'Лобстер', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'მიდიები', name_en: 'Mussels', name_ru: 'Мидии', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'ორაგული', name_en: 'Salmon', name_ru: 'Лосось', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'რვაფეხა', name_en: 'Octopus', name_ru: 'Осьминог', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'სიბასი', name_en: 'Seabass', name_ru: 'Сибас', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'ტუნას ფილე', name_en: 'Tuna fillet', name_ru: 'Филе тунца', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'ხიზილალა', name_en: 'Caviar', name_ru: 'Икра', category_ka: 'ზღვის პროდუქტები', category_en: 'Seafood', category_ru: 'Морепродукты', defaultUnit: 'კგ' },
    { name_ka: 'არაჟანი', name_en: 'Sour cream', name_ru: 'Сметана', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'არაჟანი ნაღებით', name_en: 'Sour cream with cream', name_ru: 'Сметана со сливками', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'ბურატა', name_en: 'Burrata', name_ru: 'Буррата', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'ცალი' },
    { name_ka: 'იმერული ყველი', name_en: 'Imeretian cheese', name_ru: 'Имеретинский сыр', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'კრემ ყველი', name_en: 'Cream cheese', name_ru: 'Сливочный сыр', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'ლურჯი ყველი', name_en: 'Blue cheese', name_ru: 'Голубой сыр', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'ნადუღი', name_en: 'Nadugi', name_ru: 'Надуги', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'ნაღები 35,1 %', name_en: 'Cream 35.1%', name_ru: 'Сливки 35,1%', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'ლიტრი' },
    { name_ka: 'ნაღები პრეზიდენტი 18%', name_en: 'President cream 18%', name_ru: 'Сливки Президент 18%', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'ლიტრი' },
    { name_ka: 'ნაყინი', name_en: 'Ice cream', name_ru: 'Мороженое', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'პარმეზანი', name_en: 'Parmesan', name_ru: 'Пармезан', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'პრესილი ყველი მწარე წიწაკით', name_en: 'Pressed cheese with hot pepper', name_ru: 'Прессованный сыр с острым перцем', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'პრესილი ყველი საფერავში დაძველებული', name_en: 'Pressed cheese aged in Saperavi', name_ru: 'Прессованный сыр, выдержанный в Саперави', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'რძე', name_en: 'Milk', name_ru: 'Молоко', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'ლიტრი' },
    { name_ka: 'სულგუნი', name_en: 'Sulguni', name_ru: 'Сулгуни', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'სულგუნი პიტნით', name_en: 'Sulguni with mint', name_ru: 'Сулгуни с мятой', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'ტომი ყველი', name_en: 'Tomi cheese', name_ru: 'Сыр Томи', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'ფეტა', name_en: 'Feta', name_ru: 'Фета', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'შებოლილი სულგუნი', name_en: 'Smoked Sulguni', name_ru: 'Копченый сулгуни', category_ka: 'რძის პროდუქტები და ყველი', category_en: 'Dairy products and cheese', category_ru: 'Молочные продукты и сыр', defaultUnit: 'კგ' },
    { name_ka: 'ავოკადო', name_en: 'Avocado', name_ru: 'Авокадо', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ატამი', name_en: 'Peach', name_ru: 'Персик', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ახალი კარტოფილი', name_en: 'New potato', name_ru: 'Молодой картофель', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ბაზილიკი', name_en: 'Basil', name_ru: 'Базилик', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'შეკვრა' },
    { name_ka: 'ბერი მიქსი (კენკრა)', name_en: 'Berry mix', name_ru: 'Ягодный микс', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ბოლოკი', name_en: 'Radish', name_ru: 'Редис', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ბროკოლი', name_en: 'Broccoli', name_ru: 'Брокколи', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ბროწეული', name_en: 'Pomegranate', name_ru: 'Гранат', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ბულგარული წიწაკა', name_en: 'Bell pepper', name_ru: 'Болгарский перец', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ბულგარული წითელი', name_en: 'Red bell pepper', name_ru: 'Красный болгарский перец', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'გრეიფფრუტი', name_en: 'Grapefruit', name_ru: 'Грейпфрут', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'გოგრა', name_en: 'Pumpkin', name_ru: 'Тыква', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ვაშლატამა', name_en: 'Nectarine', name_ru: 'Нектарин', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ვაშლი', name_en: 'Apple', name_ru: 'Яблоко', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ზეთისხილი შავი უკურკო', name_en: 'Black olives pitted', name_ru: 'Черные оливки без косточек', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ისპანახი', name_en: 'Spinach', name_ru: 'Шпинат', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'კამა', name_en: 'Dill', name_ru: 'Укроп', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'შეკვრა' },
    { name_ka: 'კანგაცლილი პომიდორი', name_en: 'Peeled tomato', name_ru: 'Очищенные помидоры', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'კაპერსი', name_en: 'Capers', name_ru: 'Каперсы', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'კარტოფილი', name_en: 'Potato', name_ru: 'Картофель', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'კენკრის მიქსი', name_en: 'Berry mix', name_ru: 'Ягодный микс', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'კივი', name_en: 'Kiwi', name_ru: 'Киви', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'კიტრი', name_en: 'Cucumber', name_ru: 'Огурец', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'კომბოსტო', name_en: 'Cabbage', name_ru: 'Капуста', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'კოწახური', name_en: 'Barberry', name_ru: 'Барбарис', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'კურაგა', name_en: 'Dried apricot', name_ru: 'Курага', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ლაიმი', name_en: 'Lime', name_ru: 'Лайм', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ლეღვი', name_en: 'Fig', name_ru: 'Инжир', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ლეღვის მურაბა', name_en: 'Fig jam', name_ru: 'Инжирное варенье', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ლიმონი', name_en: 'Lemon', name_ru: 'Лимон', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'მანდარინი', name_en: 'Tangerine', name_ru: 'Мандарин', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'მარწყვი', name_en: 'Strawberry', name_ru: 'Клубника', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'მწვანე ზეთისხილი უკურკო', name_en: 'Green olives pitted', name_ru: 'Зеленые оливки без косточек', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'მწვანე წიწაკა', name_en: 'Green pepper', name_ru: 'Зеленый перец', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'მწვანე ხახვი', name_en: 'Green onion', name_ru: 'Зеленый лук', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'შეკვრა' },
    { name_ka: 'ნიახურის ბოლქვი', name_en: 'Celery root', name_ru: 'Корень сельдерея', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ნიგოზი', name_en: 'Walnut', name_ru: 'Грецкий орех', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ნიორი', name_en: 'Garlic', name_ru: 'Чеснок', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ნუში', name_en: 'Almond', name_ru: 'Миндаль', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ოხრახუში', name_en: 'Parsley', name_ru: 'Петрушка', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'შეკვრა' },
    { name_ka: 'პიტნა', name_en: 'Mint', name_ru: 'Мята', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'შეკვრა' },
    { name_ka: 'პომიდორი', name_en: 'Tomato', name_ru: 'Помидор', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'პომიდორი ტოტით', name_en: 'Tomato on the vine', name_ru: 'Помидор на ветке', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'რეჰანი', name_en: 'Basil', name_ru: 'Базилик', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'შეკვრა' },
    { name_ka: 'როზმარინი', name_en: 'Rosemary', name_ru: 'Розмарин', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'შეკვრა' },
    { name_ka: 'რომანო (სალათის ფოთოლი)', name_en: 'Romaine (lettuce)', name_ru: 'Ромэн (салат)', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'რუკოლა', name_en: 'Arugula', name_ru: 'Руккола', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'სალათის ფოთოლი', name_en: 'Lettuce', name_ru: 'Салат-латук', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'სიმინდი', name_en: 'Corn', name_ru: 'Кукуруза', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'სტაფილო', name_en: 'Carrot', name_ru: 'Морковь', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ტარხუნა', name_en: 'Tarragon', name_ru: 'Тархун', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'შეკვრა' },
    { name_ka: 'ტრიუფელი', name_en: 'Truffle', name_ru: 'Трюфель', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ფერადი ჩერი', name_en: 'Colored cherry', name_ru: 'Разноцветные черри', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ფორთოხალი', name_en: 'Orange', name_ru: 'Апельсин', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ფრანგული ლობიო', name_en: 'French beans', name_ru: 'Французская фасоль', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ფრი', name_en: 'French fries', name_ru: 'Картофель фри', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ყაბახი', name_en: 'Zucchini', name_ru: 'Кабачок', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ყვავილოვანი კომბოსტო', name_en: 'Cauliflower', name_ru: 'Цветная капуста', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ყურძენი', name_en: 'Grape', name_ru: 'Виноград', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'შაშკვლავი', name_en: 'Shashkvlavi', name_ru: 'Шашквилави', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'შეკვრა' },
    { name_ka: 'შიტაკე (სოკო)', name_en: 'Shiitake (mushroom)', name_ru: 'Шиитаке (гриб)', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ჩერი', name_en: 'Cherry', name_ru: 'Черри', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ჩერი პომიდორი', name_en: 'Cherry tomato', name_ru: 'Помидор черри', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ჩინური კომბოსტო', name_en: 'Chinese cabbage', name_ru: 'Китайская капуста', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'წითელი კომბოსტო', name_en: 'Red cabbage', name_ru: 'Краснокочанная капуста', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'წითელი ხახვი', name_en: 'Red onion', name_ru: 'Красный лук', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ჭარხალი', name_en: 'Beetroot', name_ru: 'Свекла', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ხახვი (ჩვეულებრივი)', name_en: 'Onion (regular)', name_ru: 'Лук (обычный)', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ხის სოკო', name_en: 'Wood mushroom', name_ru: 'Древесный гриб', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ხურმა', name_en: 'Persimmon', name_ru: 'Хурма', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ჯინჯერი', name_en: 'Ginger', name_ru: 'Имбирь', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'ჯონჯოლი', name_en: 'Jonjoli', name_ru: 'Джонджоли', category_ka: 'ბოსტნეული, ხილი, თხილი და მწვანილი', category_en: 'Vegetables, fruits, nuts and herbs', category_ru: 'Овощи, фрукты, орехи и зелень', defaultUnit: 'კგ' },
    { name_ka: 'MSG (real)', name_en: 'MSG (real)', name_ru: 'MSG (настоящий)', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'ატრია (პასტა)', name_en: 'Noodles (pasta)', name_ru: 'Лапша (паста)', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'ბრინჯი', name_en: 'Rice', name_ru: 'Рис', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'ბრინჯის ფირფიტა', name_en: 'Rice paper', name_ru: 'Рисовая бумага', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'შეკვრა' },
    { name_ka: 'გოგრის თესლი', name_en: 'Pumpkin seed', name_ru: 'Тыквенные семечки', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'თაფლი', name_en: 'Honey', name_ru: 'Мед', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'კვერცხი', name_en: 'Egg', name_ru: 'Яйцо', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'ცალი' },
    { name_ka: 'კინოა', name_en: 'Quinoa', name_ru: 'Киноа', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'ლობიო', name_en: 'Bean', name_ru: 'Фасоль', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'მანანის ბურღული', name_en: 'Semolina', name_ru: 'Манная крупа', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'მზესუმზირა', name_en: 'Sunflower seed', name_ru: 'Семена подсолнечника', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'მუხუდო', name_en: 'Chickpea', name_ru: 'Нут', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'ოსპი წითელი', name_en: 'Red lentil', name_ru: 'Красная чечевица', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'პანკო', name_en: 'Panko', name_ru: 'Панко', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'სემოლა', name_en: 'Semola', name_ru: 'Семола', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'სუკი', name_en: 'Suki', name_ru: 'Суки', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'ტემპურა', name_en: 'Tempura', name_ru: 'Темпура', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'ტომატის კონსერვი', name_en: 'Canned tomato', name_ru: 'Консервированные помидоры', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'ფქვილი (la familia)', name_en: 'Flour (la familia)', name_ru: 'Мука (la familia)', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'შვრიის ფანტელი სოლნიშკო', name_en: 'Oat flakes Solnyshko', name_ru: 'Овсяные хлопья Солнышко', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'წიწიბურა', name_en: 'Buckwheat', name_ru: 'Гречка', category_ka: 'ბურღულეული, ფქვილი და სხვა მშრალი პროდუქტები', category_en: 'Cereals, flour and other dry products', category_ru: 'Крупы, мука и другие сухие продукты', defaultUnit: 'კგ' },
    { name_ka: 'ბალზამიკო', name_en: 'Balsamic', name_ru: 'Бальзамик', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'დემიგლასის სოუსი', name_en: 'Demi-glace sauce', name_ru: 'Соус демиглас', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'დიჟონის მდოგვი', name_en: 'Dijon mustard', name_ru: 'Дижонская горчица', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'კგ' },
    { name_ka: 'დრესინგი ქართული სალათის', name_en: 'Dressing for Georgian salad', name_ru: 'Заправка для грузинского салата', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'ზღვის პროდუქტების სალათის დრესინგი', name_en: 'Seafood salad dressing', name_ru: 'Заправка для салата из морепродуктов', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'თევზის სოუსი', name_en: 'Fish sauce', name_ru: 'Рыбный соус', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'კეჩუბი', name_en: 'Ketchup', name_ru: 'Кетчуп', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'კგ' },
    { name_ka: 'კიმჩის სოუსი', name_en: 'Kimchi sauce', name_ru: 'Соус кимчи', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'კგ' },
    { name_ka: 'ლიმონის სიროფი', name_en: 'Lemon syrup', name_ru: 'Лимонный сироп', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'ლიმონის სოუსი', name_en: 'Lemon sauce', name_ru: 'Лимонный соус', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'მაიონეზი', name_en: 'Mayonnaise', name_ru: 'Майонез', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'კგ' },
    { name_ka: 'მანგოს პიურე', name_en: 'Mango puree', name_ru: 'Пюре из манго', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'კგ' },
    { name_ka: 'მარაკუიას პიურე', name_en: 'Passion fruit puree', name_ru: 'Пюре из маракуйи', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'კგ' },
    { name_ka: 'მაყვლის წვენი', name_en: 'Blackberry juice', name_ru: 'Ежевичный сок', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'მირინი', name_en: 'Mirin', name_ru: 'Мирин', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'მისოს პასტა', name_en: 'Miso paste', name_ru: 'Мисо-паста', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'კგ' },
    { name_ka: 'მწვანე ტყემალი', name_en: 'Green tkemali', name_ru: 'Зеленый ткемали', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'კგ' },
    { name_ka: 'ოისტერ სოუსი', name_en: 'Oyster sauce', name_ru: 'Устричный соус', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'პალმის ზეთი', name_en: 'Palm oil', name_ru: 'Пальмовое масло', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'სოიოს სოუსი', name_en: 'Soy sauce', name_ru: 'Соевый соус', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'სრირაჩა', name_en: 'Sriracha', name_ru: 'Шрирача', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'კგ' },
    { name_ka: 'ტერიაკი სოუსი', name_en: 'Teriyaki sauce', name_ru: 'Соус терияки', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'ტკბილ-ცხარე სოუსი', name_en: 'Sweet and sour sauce', name_ru: 'Кисло-сладкий соус', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'ძმარი', name_en: 'Vinegar', name_ru: 'Уксус', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'ლიტრი' },
    { name_ka: 'წითელი აჯიკა', name_en: 'Red adjika', name_ru: 'Красная аджика', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'კგ' },
    { name_ka: 'წითელი ტყემალი', name_en: 'Red tkemali', name_ru: 'Красный ткемали', category_ka: 'სოუსები და პიურეები', category_en: 'Sauces and purees', category_ru: 'Соусы и пюре', defaultUnit: 'კგ' },
    { name_ka: 'ვანილი', name_en: 'Vanilla', name_ru: 'Ваниль', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'დარიჩინი', name_en: 'Cinnamon', name_ru: 'Корица', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'დაფნის ფოთოლი', name_en: 'Bay leaf', name_ru: 'Лавровый лист', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'დაღერღილი', name_en: 'Crushed pepper', name_ru: 'Дробленый перец', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'ზღვის მარილი', name_en: 'Sea salt', name_ru: 'Морская соль', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'კარტოფილის სახამებელი', name_en: 'Potato starch', name_ru: 'Картофельный крахмал', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'კუმინი', name_en: 'Cumin', name_ru: 'Кумин', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'მარილი', name_en: 'Salt', name_ru: 'Соль', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'მშრალი აჯიკა', name_en: 'Dry adjika', name_ru: 'Сухая аджика', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'ორეგანო', name_en: 'Oregano', name_ru: 'Орегано', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'პაპრიკა', name_en: 'Paprika', name_ru: 'Паприка', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'პილპილი', name_en: 'Pepper', name_ru: 'Перец', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'საფუარი', name_en: 'Yeast', name_ru: 'Дрожжи', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'სიმინდის სახამებელი (კრახმალი)', name_en: 'Corn starch', name_ru: 'Кукурузный крахмал', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'სოდა', name_en: 'Baking soda', name_ru: 'Сода', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'უცხო სუნელი', name_en: 'Utskho suneli', name_ru: 'Уцхо-сунели', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'ყავისფერი შაქარი', name_en: 'Brown sugar', name_ru: 'Коричневый сахар', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'შაფრანი', name_en: 'Saffron', name_ru: 'Шафран', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'შაქარი', name_en: 'Sugar', name_ru: 'Сахар', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'შაქრის პუდრა', name_en: 'Powdered sugar', name_ru: 'Сахарная пудра', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'ცომის გამაფხვიერებელი', name_en: 'Baking powder', name_ru: 'Разрыхлитель', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'ქონდარი', name_en: 'Savory', name_ru: 'Чабер', category_ka: 'სუნელები და სანელებლები', category_en: 'Spices and seasonings', category_ru: 'Специи и приправы', defaultUnit: 'კგ' },
    { name_ka: 'ზეთი (მზესუმზირა)', name_en: 'Oil (sunflower)', name_ru: 'Масло (подсолнечное)', category_ka: 'ზეთები და ცხიმები', category_en: 'Oils and fats', category_ru: 'Масла и жиры', defaultUnit: 'ლიტრი' },
    { name_ka: 'ზეითუნის ზეთი ეკონომი', name_en: 'Olive oil economy', name_ru: 'Оливковое масло эконом', category_ka: 'ზეთები და ცხიმები', category_en: 'Oils and fats', category_ru: 'Масла и жиры', defaultUnit: 'ლიტრი' },
    { name_ka: 'ზეითუნის ზეთი პრემიმუმი', name_en: 'Olive oil premium', name_ru: 'Оливковое масло премиум', category_ka: 'ზეთები და ცხიმები', category_en: 'Oils and fats', category_ru: 'Масла и жиры', defaultUnit: 'ლიტრი' },
    { name_ka: 'კარაქი ეკონომ', name_en: 'Butter economy', name_ru: 'Сливочное масло эконом', category_ka: 'ზეთები და ცხიმები', category_en: 'Oils and fats', category_ru: 'Масла и жиры', defaultUnit: 'კგ' },
    { name_ka: 'კარაქი პრემიმუმ', name_en: 'Butter premium', name_ru: 'Сливочное масло премиум', category_ka: 'ზეთები და ცხიმები', category_en: 'Oils and fats', category_ru: 'Масла и жиры', defaultUnit: 'კგ' },
    { name_ka: 'კახური ზეთი', name_en: 'Kakhetian oil', name_ru: 'Кахетинское масло', category_ka: 'ზეთები და ცხიმები', category_en: 'Oils and fats', category_ru: 'Масла и жиры', defaultUnit: 'ლიტრი' },
    { name_ka: 'ფრიტიურის ზეთი', name_en: 'Frying oil', name_ru: 'Масло для фритюра', category_ka: 'ზეთები და ცხიმები', category_en: 'Oils and fats', category_ru: 'Масла и жиры', defaultUnit: 'ლიტრი' },
    { name_ka: 'შავი სეზამის მარცვლები', name_en: 'Black sesame seeds', name_ru: 'Черные семена кунжута', category_ka: 'ზეთები და ცხიმები', category_en: 'Oils and fats', category_ru: 'Масла и жиры', defaultUnit: 'კგ' },
    { name_ka: 'Prosecco (ცივი სასმელი)', name_en: 'Prosecco (cold drink)', name_ru: 'Просекко (холодный напиток)', category_ka: 'სასმელები (უალკოჰოლო)', category_en: 'Beverages (non-alcoholic)', category_ru: 'Напитки (безалкогольные)', defaultUnit: 'ცალი' },
    { name_ka: 'Tea Black (ჩაი)', name_en: 'Black Tea', name_ru: 'Черный чай', category_ka: 'სასმელები (უალკოჰოლო)', category_en: 'Beverages (non-alcoholic)', category_ru: 'Напитки (безалкогольные)', defaultUnit: 'კგ' },
    { name_ka: 'ვაშლის წვენი', name_en: 'Apple juice', name_ru: 'Яблочный сок', category_ka: 'სასმელები (უალკოჰოლო)', category_en: 'Beverages (non-alcoholic)', category_ru: 'Напитки (безалкогольные)', defaultUnit: 'ლიტრი' },
    { name_ka: 'ბორჯომი (მინერალური წყალი)', name_en: 'Borjomi (mineral water)', name_ru: 'Боржоми (минеральная вода)', category_ka: 'სასმელები (უალკოჰოლო)', category_en: 'Beverages (non-alcoholic)', category_ru: 'Напитки (безалкогольные)', defaultUnit: 'ცალი' },
    { name_ka: 'კარკადე ჩაი', name_en: 'Karkade tea', name_ru: 'Чай каркаде', category_ka: 'სასმელები (უალკოჰოლო)', category_en: 'Beverages (non-alcoholic)', category_ru: 'Напитки (безалкогольные)', defaultUnit: 'კგ' },
    { name_ka: 'პიტნა1 (ჩაი/მცენარე)', name_en: 'Mint1 (tea/plant)', name_ru: 'Мята1 (чай/растение)', category_ka: 'სასმელები (უალკოჰოლო)', category_en: 'Beverages (non-alcoholic)', category_ru: 'Напитки (безалкогольные)', defaultUnit: 'შეკვრა' },
    { name_ka: 'ტონიკი', name_en: 'Tonic', name_ru: 'Тоник', category_ka: 'სასმელები (უალკოჰოლო)', category_en: 'Beverages (non-alcoholic)', category_ru: 'Напитки (безалкогольные)', defaultUnit: 'ცალი' },
    { name_ka: 'ტონიკი 0.330 მლ', name_en: 'Tonic 0.330 ml', name_ru: 'Тоник 0,330 мл', category_ka: 'სასმელები (უალკოჰოლო)', category_en: 'Beverages (non-alcoholic)', category_ru: 'Напитки (безалкогольные)', defaultUnit: 'ცალი' },
    { name_ka: 'ფორთოხლის წვენი', name_en: 'Orange juice', name_ru: 'Апельсиновый сок', category_ka: 'სასმელები (უალკოჰოლო)', category_en: 'Beverages (non-alcoholic)', category_ru: 'Напитки (безалкогольные)', defaultUnit: 'ლიტრი' },
    { name_ka: 'ყავა ალვორადა ვენერ კაფე', name_en: 'Coffee Alvorada Wiener Kaffee', name_ru: 'Кофе Alvorada Wiener Kaffee', category_ka: 'სასმელები (უალკოჰოლო)', category_en: 'Beverages (non-alcoholic)', category_ru: 'Напитки (безалкогольные)', defaultUnit: 'კგ' },
    { name_ka: 'ყავა ბრაზილიური მედიუმი', name_en: 'Brazilian medium coffee', name_ru: 'Бразильский кофе медиум', category_ka: 'სასმელები (უალკოჰოლო)', category_en: 'Beverages (non-alcoholic)', category_ru: 'Напитки (безалкогольные)', defaultUnit: 'კგ' },
    { name_ka: 'წყალი', name_en: 'Water', name_ru: 'Вода', category_ka: 'სასმელები (უალკოჰოლო)', category_en: 'Beverages (non-alcoholic)', category_ru: 'Напитки (безалкогольные)', defaultUnit: 'ლიტრი' },
    { name_ka: 'ბაგეტი', name_en: 'Baguette', name_ru: 'Багет', category_ka: 'სხვა პროდუქტები', category_en: 'Other products', category_ru: 'Другие продукты', defaultUnit: 'ცალი' },
    { name_ka: 'ეკალა', name_en: 'Ekala', name_ru: 'Экала', category_ka: 'სხვა პროდუქტები', category_en: 'Other products', category_ru: 'Другие продукты', defaultUnit: 'კგ' },
    { name_ka: 'ჟელატინი', name_en: 'Gelatin', name_ru: 'Желатин', category_ka: 'სხვა პროდუქტები', category_en: 'Other products', category_ru: 'Другие продукты', defaultUnit: 'კგ' },
    { name_ka: 'მაწონი', name_en: 'Matsoni', name_ru: 'Мацони', category_ka: 'სხვა პროდუქტები', category_en: 'Other products', category_ru: 'Другие продукты', defaultUnit: 'კგ' },
    { name_ka: 'მჭადის ფქვილი', name_en: 'Mchadi flour', name_ru: 'Мчади мука', category_ka: 'სხვა პროდუქტები', category_en: 'Other products', category_ru: 'Другие продукты', defaultUnit: 'კგ' },
    { name_ka: 'პური', name_en: 'Bread', name_ru: 'Хлеб', category_ka: 'სხვა პროდუქტები', category_en: 'Other products', category_ru: 'Другие продукты', defaultUnit: 'ცალი' },
    { name_ka: 'ყინული', name_en: 'Ice', name_ru: 'Лед', category_ka: 'სხვა პროდუქტები', category_en: 'Other products', category_ru: 'Другие продукты', defaultUnit: 'კგ' },
    { name_ka: 'ყინულის კუბები', name_en: 'Ice cubes', name_ru: 'Кубики льда', category_ka: 'სხვა პროდუქტები', category_en: 'Other products', category_ru: 'Другие продукты', defaultUnit: 'კგ' },
];

export const PRODUCTS: Product[] = [
    ...sakhinkleProductsRaw.map((p, i) => ({ ...p, id: `prod-s-${i+1}`, restaurants: [Restaurant.SAKHINKLE] })),
    ...midiebiProductsRaw.map((p, i) => ({ ...p, id: `prod-m-${i+1}`, restaurants: [Restaurant.MIDIEBI] })),
];

// FIX: Add PRODUCT_CATEGORIES export to resolve import error in ManagementView.tsx.
const getProductCategories = (): Record<Language, string[]> => {
    const catKaSet = new Set<string>();
    const catEnSet = new Set<string>();
    const catRuSet = new Set<string>();
  
    PRODUCTS.forEach(p => {
        catKaSet.add(p.category_ka);
        catEnSet.add(p.category_en);
        catRuSet.add(p.category_ru);
    });
  
    return {
      ka: [...catKaSet].sort((a, b) => a.localeCompare(b, 'ka-GE')),
      en: [...catEnSet].sort(),
      ru: [...catRuSet].sort(),
    };
};

export const PRODUCT_CATEGORIES = getProductCategories();

export const ACCESS_CODES = {
  '0001': Restaurant.MIDIEBI,
  '0002': Restaurant.SAKHINKLE,
  '606587': 'ADMIN',
};

export const CHEFS: Record<Restaurant, string[]> = {
  [Restaurant.MIDIEBI]: ['მარიამი', 'მიშო', 'ნასტია'],
  [Restaurant.SAKHINKLE]: ['ლუკა', 'ალექსი', 'მადონა', 'მარიამი'],
};

export const SUPPLIERS: string[] = [
    'აგროჰაბი',
    'კარფური',
    'გუდვილი',
    'ნიკორა',
    'ადგილობრივი ბაზარი',
    'სხვა',
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  ka: {
    searchPlaceholder: 'პროდუქტის ძებნა...',
    newOrder: 'ახალი შეკვეთა',
    logout: 'გასვლა',
    addCustomItemTitle: 'სხვა პროდუქტის დამატება',
    itemName: 'პროდუქტის დასახელება',
    itemUnit: 'ერთეული',
    itemCategory: 'კატეგორია',
    selectCategory: 'აირჩიეთ კატეგორია',
    addNewCategory: 'ახალი კატეგორიის დამატება',
    newCategoryName: 'ახალი კატეგორიის სახელი',
    addItem: 'დამატება',
    currentOrder: 'მიმდინარე შეკვეთა',
    chef: 'მზარეული',
    selectYourName: 'აირჩიეთ თქვენი სახელი',
    // FIX: Add 'selectChef' translation for ChefView component
    selectChef: 'აირჩიეთ მზარეული',
    noProductsAdded: 'პროდუქტები არ არის დამატებული.',
    submitOrder: 'შეკვეთის გაგზავნა',
    alertFillFields: 'გთხოვთ შეავსოთ ყველა ველი და დაამატოთ პროდუქტები.',
    orderSent: 'შეკვეთა წარმატებით გაიგზავნა!',
  },
  en: {
    searchPlaceholder: 'Search for products...',
    newOrder: 'New Order',
    logout: 'Logout',
    addCustomItemTitle: 'Add Custom Item',
    itemName: 'Item Name',
    itemUnit: 'Unit',
    itemCategory: 'Category',
    selectCategory: 'Select Category',
    addNewCategory: 'Add New Category',
    newCategoryName: 'New Category Name',
    addItem: 'Add Item',
    currentOrder: 'Current Order',
    chef: 'Chef',
    selectYourName: 'Select Your Name',
    // FIX: Add 'selectChef' translation for ChefView component
    selectChef: 'Select Chef',
    noProductsAdded: 'No products have been added.',
    submitOrder: 'Submit Order',
    alertFillFields: 'Please fill all fields and add products to the order.',
    orderSent: 'Order sent successfully!',
  },
  ru: {
    searchPlaceholder: 'Поиск продуктов...',
    newOrder: 'Новый заказ',
    logout: 'Выйти',
    addCustomItemTitle: 'Добавить свой продукт',
    itemName: 'Название продукта',
    itemUnit: 'Единица',
    itemCategory: 'Категория',
    selectCategory: 'Выберите категорию',
    addNewCategory: 'Добавить новую категорию',
    newCategoryName: 'Название новой категории',
    addItem: 'Добавить',
    currentOrder: 'Текущий заказ',
    chef: 'Повар',
    selectYourName: 'Выберите ваше имя',
    // FIX: Add 'selectChef' translation for ChefView component
    selectChef: 'Выберите повара',
    noProductsAdded: 'Продукты не добавлены.',
    submitOrder: 'Отправить заказ',
    alertFillFields: 'Пожалуйста, заполните все поля и добавьте продукты в заказ.',
    orderSent: 'Заказ успешно отправлен!',
  },
};
